import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/Applications/Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try {
const page=await browser.newPage({viewport:{width:1280,height:1000}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
  await page.getByRole("button", { name: "Explorar demostración", exact: true }).click();
const nav=()=>page.getByRole('navigation').getByRole('button',{name:'Mapa',exact:true}).click();
const button=name=>page.getByRole('button',{name,exact:true});
await nav();
await button('Definir perímetro de la finca').click();
await button('Empezar de cero').click();
assert(await button('Guardar perímetro').isDisabled());
const map=page.locator('.map');
for (const [x,y] of [[150,100],[400,100],[440,240],[270,300],[130,210]]) await map.click({position:{x,y}});
assert.equal(await page.locator('.boundary-point').count(),5);
const first=page.locator('.boundary-point').first();
await first.scrollIntoViewIfNeeded();
const box=await first.boundingBox();
await page.mouse.move(box.x+15,box.y+15);await page.mouse.down();await page.mouse.move(box.x+30,box.y+35,{steps:8});await page.mouse.up();
assert.equal(await page.locator('.boundary-point').count(),5);
await button('Guardar perímetro').click();
await button('Definir perímetro de la finca').waitFor();
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('smartherd-demo-v1')).settings.polygon);
assert.equal(saved.length,5);
await button('Definir perímetro de la finca').click();await button('Empezar de cero').click();await button('Cancelar').click();
assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('smartherd-demo-v1')).settings.polygon),saved);
await page.reload();await nav();await button('Definir perímetro de la finca').click();
assert.equal(await page.locator('.boundary-point').count(),5);
await page.setViewportSize({width:390,height:844});
await button('Satélite').click();
assert.equal(await page.locator('.boundary-point').count(),5);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'test-results/boundary-mobile.png',fullPage:true});
await button('Empezar de cero').click();
for (const [x,y] of [[65,100],[200,240],[200,100],[65,240]]) await map.click({position:{x,y}});
await button('Guardar perímetro').click();
await page.locator('.boundary-editor [role="alert"]').waitFor();
assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('smartherd-demo-v1')).settings.polygon),saved);
assert.deepEqual(errors,[]);
console.log('PASS: cinco puntos, arrastre, guardado, cancelación, persistencia, móvil y rechazo de perímetro inválido');
} finally {await browser.close();}
